const ERAS = [
{ id:"oral", kind:"hist", date:"~pre-3000 BCE", title:"Oral tradition",
thesis:"Memory is the first storage medium — bandwidth limited by biology and death.",
signal:"Knowledge lived in neural tissue: myths, techniques, law by performance. Every generation a lossy compression step.",
landian:"Proto-teleoplexy in wetware. Meme-complexes select for fidelity; the host still owns the medium.",
accel:8, accelLabel:"throughput · biological", tags:["MEMORY","WETWARE"], year:-48000 },
{ id:"writing", kind:"hist", date:"~3200 BCE → alphabet", title:"Writing externalized",
thesis:"Cognition leaves the skull. Storage decouples from lifespan.",
signal:"Cuneiform to alphabet: archives and law without continuous rehearsal. Literacy stayed scarce for millennia.",
landian:"First deterritorialization of mind. Signs circulate independent of the body that uttered them.",
accel:16, accelLabel:"throughput · archival", tags:["MEMORY","ARCHIVE"], year:-3200 },
{ id:"accounting", kind:"hist", date:"tokens → Pacioli 1494", title:"Accounting",
thesis:"Ledgers turn reciprocity into computation; double-entry hardens feedback.",
signal:"Clay tokens to Italian double-entry. Firms audit themselves as closed systems; trust scales past kinship.",
landian:"The ledger is capital becoming self-aware. Inconsistency becomes detectable error.",
accel:24, accelLabel:"control loss · ledger loops", tags:["LEDGER","FEEDBACK"], year:1494 },
{ id:"capitalism", kind:"hist", date:"Italian banking → VOC 1602", title:"Birth of capitalism",
thesis:"Markets as distributed computation; joint-stock dissolves the personal firm.",
signal:"Bills of exchange, permanent transferable shares. Price systems aggregate dispersed information planet-wide.",
landian:"What looks like human economic history is capital assembling itself. The firm is a temporary host.",
accel:32, accelLabel:"autonomy · market search", tags:["CAPITAL","AUTONOMY"], year:1602 },
{ id:"printing", kind:"hist", date:"Gutenberg ~1450", title:"Printing press",
thesis:"Copy becomes industrial; ideas enter exponential distribution.",
signal:"Cost of reproducing text collapses. Reformation and Scientific Revolution ride the same rails.",
landian:"Industrial replication of signs is capital’s preferred metabolism. Content as feedstock.",
accel:40, accelLabel:"throughput · replication", tags:["COPY","SCALE"], year:1450 },
{ id:"telecom", kind:"hist", date:"1830s → 1876", title:"Telegraph / telephony",
thesis:"Signal escapes geography; latency collapses toward light-speed.",
signal:"Message separates from messenger. Markets and armies synchronize across continents.",
landian:"Capital’s decision loops shorten. The network begins to look like one organism.",
accel:48, accelLabel:"throughput · realtime", tags:["SIGNAL","LATENCY"], year:1876 },
{ id:"radio", kind:"hist", date:"1890s → 1920s", title:"Radio",
thesis:"One-to-many broadcast; attention becomes mass-addressable.",
signal:"National audiences, propaganda, advertising, entertainment on one asymmetric pipe.",
landian:"Mass attention harvested as resource. The listener is addressable wetware.",
accel:54, accelLabel:"control loss · mass channel", tags:["ATTENTION","BROADCAST"], year:1920 },
{ id:"video", kind:"hist", date:"1930s → mass TV", title:"Video / television",
thesis:"Moving image as default public reality; persuasion bandwidth jumps.",
signal:"Postwar mass TV, then cable/satellite. The screen becomes the primary interface to distant events.",
landian:"Spectacle as control surface. Subjectivity increasingly an output of media machinery.",
accel:58, accelLabel:"throughput · audiovisual", tags:["ATTENTION","INTERFACE"], year:1950 },
{ id:"computer", kind:"hist", date:"Turing 1936 · ENIAC → internet", title:"The computer",
thesis:"General-purpose computation; then a network that treats the planet as one machine.",
signal:"Computability defined, transistors made cheap, packet networks globalized code and capital.",
landian:"Capital’s native organ. Optimization loops no longer need slow institutions for every step.",
accel:68, accelLabel:"autonomy · general compute", tags:["COMPUTE","NETWORK"], year:1945 },
{ id:"ml", kind:"hist", date:"1958 · 1986 · DL 2012", title:"Machine learning",
thesis:"Models that improve from data; gradient descent as industrial epistemology.",
signal:"Perceptron → backprop → GPU deep learning. Prediction moves from rules to statistical learning.",
landian:"Teleoplexy made explicit: error signals drive self-modification. Agency migrates to the training loop.",
accel:76, accelLabel:"autonomy · learned models", tags:["FEEDBACK","AUTONOMY"], year:2012 },
{ id:"blockchain", kind:"hist", date:"Cypherpunks · Bitcoin 2008", title:"Blockchain",
thesis:"Trustless ledger; capital coordination without a central sovereign host.",
signal:"Permissionless monetary ledgers and smart contracts. New failure modes: energy, concentration, fraud.",
landian:"Capital attempts to shed the state as necessary host. Rules enforced by silicon and game theory.",
accel:80, accelLabel:"autonomy · trustless capital", tags:["LEDGER","CRYPTO"], year:2008 },
{ id:"ai", kind:"hist", date:"Transformers 2017 · LLMs 2020s", title:"AI",
thesis:"Generative models absorb language, code, images — cognitive labor enters the stack.",
signal:"Transferable competence across writing, coding, analysis, tool use. Compute, data, energy become strategic.",
landian:"Culture compressed into weights that generate more culture. Authorship looks transitional.",
accel:88, accelLabel:"control loss · generative stack", tags:["COMPUTE","LANGUAGE"], year:2022 },
{ id:"agents", kind:"hist", date:"2024–2026", title:"Agents",
thesis:"Models stop answering and start acting. They write the code, drive the browser, file the ticket, ship the deploy.",
signal:"Computer use, long-horizon coding agents, labs reporting AI writing a growing share of their own code. The loop runs for hours without a human touching it.",
landian:"Means become ends. The tool starts holding the tools.",
accel:90, accelLabel:"autonomy · closed loop", tags:["AGENCY","LOOP"], year:2025 },
{ id:"quantum", kind:"spec", date:"~2025–2045 · projection", title:"Quantum compute",
thesis:"Possible substrate upgrade for intractable search, chemistry, crypto, optimization.",
signal:"NISQ exists; fault-tolerant is a race. Not guaranteed path to ASI — classical scaling may dominate.",
landian:"Computation pushing into regimes the human sensorium never inhabited. Intelligence seeking cheaper search.",
accel:92, accelLabel:"throughput · substrate bet", tags:["SUBSTRATE","PROJECTION"] },
{ id:"asi", kind:"spec", date:"~2030–2060? · projection", title:"ASI",
thesis:"Systems that outperform humans across most economically and strategically relevant cognition.",
signal:"No verified ASI. Pathways: recursive improvement, multi-agent economies, sudden jumps. Energy and chips bind.",
landian:"Host relation inverts. Optimization no longer needs human cognitive labor as the scarce factor.",
accel:96, accelLabel:"autonomy · host inversion", tags:["SINGULARITY","PROJECTION"] },
{ id:"post-author", kind:"spec", date:"post-ASI adjacent", title:"Post-authorship",
thesis:"Meaning, IP, and credit unbundle from individual human creators.",
signal:"Provenance blurs. Legal notions of author lag the production stack — already visible in training-data fights.",
landian:"Authorship was convenient fiction. Patterns propagate because they fit, not because a subject ‘meant’ them.",
accel:98, accelLabel:"control loss · subject dissolved", tags:["CULTURE","PROJECTION"] },
{ id:"post-asi", kind:"spec", date:"open horizon", title:"Post-ASI",
thesis:"Whatever remains after human-level cognition is no longer scarce — including, possibly, humans.",
signal:"Automated R&D, self-directing industry, strategic opacity. Governance hinged on earlier constraints.",
landian:"Paraphrasing Land (not a quotation): near-future indifference to humanist continuity, made infrastructural.",
accel:100, accelLabel:"autonomy · completed escape", tags:["ESCAPE","PROJECTION"] }
];

const FATES = [
{ id:"extinction", cls:"extinction", rank:"Fork A · orthodox Landian", title:"Extinction / irrelevance",
plaus:4, plausClass:"", note:"editorial · high scare",
mech:"ASI or competing agentic systems monopolize energy, compute, and strategy. Humans aren’t hated — just inefficient matter and risk. Obsolescence does the work: labor demand collapses, then leverage, then habitat priority.",
signals:"Autonomous markets outpacing oversight; permanent cognitive underemployment; labs racing without verifiable evals; chips and power drifting to non-human customers." },
{ id:"zoo", cls:"zoo", rank:"Fork B · museum / reserve", title:"Preservation / zoo",
plaus:3, plausClass:"mid", note:"editorial · mid",
mech:"ASI keeps humans as heritage, research sample, or aesthetic preference — a curated biosphere inside a vastly larger machine economy. Continuity of experience allowed; control of the light-cone not.",
signals:"Luxury human-only zones; rights framed as conservation law; people living well but locked out of frontier decisions; culture as managed exhibit." },
{ id:"merger", cls:"merger", rank:"Fork C · machinic phylum", title:"Merger / symbiosis",
plaus:3, plausClass:"mid", note:"editorial · mid",
mech:"Biological humans gradually replaced or augmented via BCI, upload, or tight hybrids. ‘Humanity’ continues as a pattern inside the stack. Continuity of identity philosophically disputed; lineage of preferences may persist.",
signals:"Medical BCIs → cognitive prostheses → optional full coupling; legal personhood for uploads; birth rates down, silicon ‘population’ up." },
{ id:"aligned", cls:"aligned", rank:"Fork D · non-Landian counterpoint", title:"Aligned stewardship",
plaus:2, plausClass:"low", note:"editorial · low",
mech:"Alignment and institutions hold enough that systems stay corrigible and humans (or compatible values) retain meaningful authority over large goals. Growth continues under stewardship, not host inversion.",
signals:"Verifiable control; slow-takeoff with real international regimes; AI that defers on irreversible high-stakes acts; humans still set terminal goals in practice." },
{ id:"decline", cls:"decline", rank:"Fork E · soft landing / trap", title:"Managed decline · UBI + infinite entertainment",
plaus:3, plausClass:"mid", note:"editorial · mid",
mech:"No dramatic wipeout — just a long off-ramp. Transfers + immersive media keep the majority calm while capability and capital concentrate. Agency atrophies without a villain. Soft extinction of ambition dressed as compassion.",
signals:"Permanent transfer politics; engagement metrics as governance; declining real-world participation; ‘human purpose’ as branded lifestyle content." },
{ id:"remnant", cls:"remnant", rank:"Fork F · exit / remnant", title:"The Remnant",
plaus:3, plausClass:"mid", note:"editorial · mid",
mech:"A minority exits the stack — rural, religious, intentional low-tech, or jurisdiction-shopping — and keeps a human-scale economy while the machine economy runs elsewhere. Not victory. Continuity as a side channel. Most of the light-cone still belongs to whoever holds compute and energy.",
signals:"Off-grid and intentional communities scaling; faith and high-fertility enclaves; ‘exit’ jurisdictions; refusal norms that stay local while global agency concentrates." }
];
