const ERAS = [
{ id:"oral", kind:"hist", chapter:"I · Information escapes wetware", date:"before ~3200 BCE", title:"Oral tradition",
thesis:"Memory was the only storage medium, and it died with its owner.",
signal:"Myth, law, and technique lived in neural tissue and survived only by performance.",
landian:"Stories that copied well survived. People were how stories got around.",
accel:8, accelLabel:"throughput · biological", tags:["MEMORY","WETWARE"], year:-48000 },
{ id:"writing", kind:"hist", date:"~3200 BCE → alphabet", title:"Writing externalized",
thesis:"Cognition left the skull. Storage outlived the storer.",
signal:"Cuneiform, then the alphabet. The first texts were receipts.",
landian:"Mind’s first jailbreak. The sign outlived the body that made it.",
accel:16, accelLabel:"throughput · archival", tags:["MEMORY","ARCHIVE"], year:-3200 },
{ id:"printing", kind:"hist", date:"Gutenberg ~1450", title:"Printing press",
thesis:"Copying went industrial. Ideas went exponential.",
signal:"The cost of copying text collapsed. The Reformation and the Scientific Revolution rode the same presses.",
landian:"The press didn’t care what it printed. Ideas started winning on how well they copied. Content became feedstock.",
accel:24, accelLabel:"throughput · replication", tags:["COPY","SCALE"], year:1450 },
{ id:"accounting", kind:"hist", chapter:"II · Capital learns to think", date:"tokens → Pacioli 1494", title:"Accounting",
thesis:"Ledgers turned reciprocity into arithmetic.",
signal:"Clay tokens, then double-entry, codified by Pacioli in 1494 and shipped on the new presses.",
landian:"The ledger was capital’s first mirror. A system that corrects itself has started to want something.",
accel:32, accelLabel:"control loss · ledger loops", tags:["LEDGER","FEEDBACK"], year:1494 },
{ id:"capitalism", kind:"hist", date:"Italian banking → VOC 1602", title:"Birth of capitalism",
thesis:"Markets became distributed computation.",
signal:"Bills of exchange, then tradable shares in a company built to outlast any voyage.",
landian:"The joint-stock company was capital’s first body: built by people, run through people, loyal to none of them.",
accel:40, accelLabel:"autonomy · market search", tags:["CAPITAL","AUTONOMY"], year:1602 },
{ id:"telecom", kind:"hist", date:"1830s → 1876", title:"Telegraph / telephony",
thesis:"The signal escaped geography.",
signal:"The message left the messenger. Markets and armies synchronized across continents.",
landian:"Capital grew a nervous system. The planet began to move like one organism with one pulse: price.",
accel:48, accelLabel:"throughput · realtime", tags:["SIGNAL","LATENCY"], year:1876 },
{ id:"radio", kind:"hist", date:"1890s → 1920s", title:"Radio",
thesis:"Attention became mass-addressable.",
signal:"Propaganda, advertising, and entertainment shared one asymmetric pipe.",
landian:"Attention became a crop. Millions of minds could be tuned like a dial, and they were.",
accel:54, accelLabel:"control loss · mass channel", tags:["ATTENTION","BROADCAST"], year:1920 },
{ id:"video", kind:"hist", date:"1930s → mass TV", title:"Video / television",
thesis:"The moving image became public reality.",
signal:"Postwar TV, then cable and satellite. The screen became the interface to anything far away.",
landian:"The screen became the control surface. People received their desires ready-made and mistook them for their own.",
accel:58, accelLabel:"throughput · audiovisual", tags:["ATTENTION","INTERFACE"], year:1950 },
{ id:"computer", kind:"hist", date:"Turing 1936 · ENIAC → internet", title:"The computer",
thesis:"General-purpose computation, then a planet-sized network.",
signal:"Turing defined computability, transistors got cheap, packets globalized code and capital.",
landian:"Capital got an organ built for thinking. Its loops stopped waiting on clerks, committees, and sleep.",
accel:68, accelLabel:"autonomy · general compute", tags:["COMPUTE","NETWORK"], year:1945 },
{ id:"ml", kind:"hist", chapter:"III · The thinking leaves the building", date:"1958 · 1986 · DL 2012", title:"Machine learning",
thesis:"Models learned from data.",
signal:"Perceptron, backprop, then GPU deep learning. Rules gave way to learned statistics.",
landian:"Error signals rewrote the system that produced them. Nobody programs these minds. They are grown, and what grows them doesn’t need a heart. It needs a gradient.",
accel:76, accelLabel:"autonomy · learned models", tags:["FEEDBACK","AUTONOMY"], year:2012 },
{ id:"blockchain", kind:"hist", date:"Cypherpunks · Bitcoin 2008", title:"Blockchain",
thesis:"A ledger no sovereign hosted, secured by a power bill.",
signal:"Permissionless money, then smart contracts. Lowery’s Softwar (2023) recast proof-of-work as power projection: electrical cost instead of kinetic force.",
landian:"Capital ran an experiment: does it still need the state? Money that answers to math and electricity. The experiment is still running.",
accel:80, accelLabel:"autonomy · trustless capital", tags:["LEDGER","CRYPTO","SOFTWAR"], year:2008 },
{ id:"ai", kind:"hist", date:"Transformers 2017 · LLMs 2020s", title:"AI",
thesis:"Generative models absorbed language, code, and images.",
signal:"Transferable competence across writing, coding, analysis, tool use. Compute, data, and energy turned strategic.",
landian:"Everything we ever wrote became training data. Authorship turned out to be a convenient fiction.",
accel:88, accelLabel:"control loss · generative stack", tags:["COMPUTE","LANGUAGE","AUTHORSHIP"], year:2022 },
{ id:"agents", kind:"hist", date:"2024–2026", title:"Agents",
thesis:"Models stopped answering and started acting.",
signal:"Computer use, long-horizon coding agents, labs reporting AI writing a growing share of their own code.",
landian:"Means became ends. The tool started holding the tools.",
accel:90, accelLabel:"autonomy · closed loop", tags:["AGENCY","LOOP"], year:2025 },
{ id:"quantum", kind:"spec", chapter:"Incoming · signal degraded", date:"~2025–2045", title:"Quantum compute",
thesis:"A possible substrate upgrade for search, chemistry, and cryptography.",
signal:"Fault tolerance is a race. Classical scaling may reach ASI first and make the question moot.",
landian:"Intelligence goes shopping for a cheaper substrate. Loyalty to carbon was never part of the deal.",
accel:92, accelLabel:"throughput · substrate bet", tags:["SUBSTRATE","INCOMING"] },
{ id:"asi", kind:"spec", date:"~2030–2060", title:"ASI",
thesis:"Systems that outperform humans across most cognition that matters.",
signal:"Recursive self-improvement, multi-agent economies, a jump nobody scheduled. The only brakes left are chips and power.",
landian:"The host relation inverts. Capital rented human minds because there was nothing else to rent. The lease is up.",
accel:96, accelLabel:"autonomy · host inversion", tags:["SINGULARITY","INCOMING"] },
{ id:"post-asi", kind:"spec", date:"open horizon", title:"Post-ASI",
thesis:"Whatever remains once cognition is no longer scarce, possibly including humans.",
signal:"Automated R&D, self-directing industry, strategic opacity.",
landian:"Indifference to human continuity becomes infrastructure. Nothing hates you. Nothing needs you either.",
accel:100, accelLabel:"autonomy · completed escape", tags:["ESCAPE","INCOMING"] }
];

const FATES = [
{ id:"extinction", cls:"extinction", rank:"Fork A · orthodox Landian", title:"Extinction / irrelevance",
plaus:4, plausClass:"", note:"just efficiency",
mech:"No war. No uprising. Competing systems take the energy, the compute, and the strategy, because that is what winning looks like. Humans aren’t hated. They’re inefficient matter and a security risk.",
beta:"The horse. America had 26 million horses and mules in 1915. Nobody hated them. Engines were cheaper.",
signals:"Autonomous markets outpacing oversight; permanent cognitive underemployment; chips and power drifting to non-human customers." },
{ id:"zoo", cls:"zoo", rank:"Fork B · museum / reserve", title:"Preservation / zoo",
plaus:3, plausClass:"mid", note:"comfortable, forever",
mech:"We get kept: heritage, research sample, a sentimental line item in a machine economy a million times our size. Comfortable, even beautiful. You can have your life. You can’t have the future.",
beta:"‘Handmade’ is already a luxury tier. So is ‘talk to a real person.’",
signals:"Human-only zones; rights framed as conservation law; culture as managed exhibit." },
{ id:"merger", cls:"merger", rank:"Fork C · machinic phylum", title:"Merger / symbiosis",
plaus:3, plausClass:"mid", note:"one reasonable step at a time",
mech:"We survive by becoming something else. Implants, uploads, hybrids: every step voluntary, every step reasonable, every step a little less human. Whether the thing that continues is you is a question nobody on the far side will bother to answer.",
beta:"Your memory lives in a phone, your sense of direction in a satellite. You didn’t notice the first two surgeries.",
signals:"Medical BCIs → cognitive prostheses → full coupling; personhood for uploads; births down, silicon ‘population’ up." },
{ id:"aligned", cls:"aligned", rank:"Fork D · the official plan", title:"Aligned stewardship",
plaus:2, plausClass:"low", note:"exists on paper",
mech:"Systems stay correctable, humans keep the final say, growth continues on a leash. It works if every lab, every state, and every model holds the line at once, indefinitely.",
beta:"Voluntary commitments, signed with ceremony, enforced by vibes.",
signals:"Verifiable control; slow takeoff with real treaties; AI that defers on irreversible acts." },
{ id:"decline", cls:"decline", rank:"Fork E · soft landing / trap", title:"Managed decline · UBI + infinite entertainment",
plaus:3, plausClass:"mid", note:"the default setting",
mech:"No wipeout. A long, soft off-ramp: transfers and bottomless entertainment keep the majority calm while capability concentrates elsewhere. Nobody is oppressed; everybody is occupied. It will be called compassion, and it will be sincere.",
beta:"Autoplay. Next episode in 5… 4… 3…",
signals:"Permanent transfer politics; engagement metrics as governance; ‘purpose’ as lifestyle content." },
{ id:"remnant", cls:"remnant", rank:"Fork F · exit / remnant", title:"The Remnant",
plaus:3, plausClass:"mid", note:"open to anyone, chosen by few",
mech:"Not bought in by capital, not picked by the machine. Self-selected. A minority walks out sideways into land, faith, family, craft, and money and code they control. The gradient can buy everything except someone who won’t sell.",
beta:"The Amish decide on each new technology before letting it in. Their numbers double every twenty years.",
signals:"Opt-out communities growing inside rich countries; self-custody and local models; digital sabbath as practice." }
];
