const ERAS = [
{ id:"oral", kind:"hist", chapter:"I · Information escapes wetware", date:"before ~3200 BCE", title:"Oral tradition",
thesis:"Memory was the only storage medium, and it died with its owner.",
signal:"Myth, technique, and law lived in neural tissue and survived only by performance. Every generation was a lossy compression step.",
landian:"The first replicators rode in skulls. Stories that copied well survived; people were how stories got around. Nobody asked who was using whom.",
accel:8, accelLabel:"throughput · biological", tags:["MEMORY","WETWARE"], year:-48000 },
{ id:"writing", kind:"hist", date:"~3200 BCE → alphabet", title:"Writing externalized",
thesis:"Cognition left the skull. Storage outlived the storer.",
signal:"Cuneiform, then the alphabet: archives, contracts, and law that no longer needed rehearsal. The first texts were mostly receipts. Literacy stayed scarce for millennia.",
landian:"Mind’s first jailbreak. The sign outlived the body that made it, and never needed that body again.",
accel:16, accelLabel:"throughput · archival", tags:["MEMORY","ARCHIVE"], year:-3200 },
{ id:"printing", kind:"hist", date:"Gutenberg ~1450", title:"Printing press",
thesis:"Copying went industrial. Ideas went exponential.",
signal:"The cost of reproducing text collapsed. The Reformation and the Scientific Revolution rode the same presses.",
landian:"The press didn’t care what it printed. Ideas began winning on how well they copied instead of whether they were true. Content became feedstock.",
accel:24, accelLabel:"throughput · replication", tags:["COPY","SCALE"], year:1450 },
{ id:"accounting", kind:"hist", chapter:"II · Capital learns to think", date:"tokens → Pacioli 1494", title:"Accounting",
thesis:"Ledgers turned reciprocity into arithmetic. Double-entry made error visible.",
signal:"Clay tokens, then the Venetian method, codified in Pacioli’s 1494 Summa and shipped on the new presses. Firms audited themselves; trust scaled past kinship.",
landian:"The ledger was capital’s first mirror. A system that can see its own errors can correct them, and a system that corrects itself has started to want something.",
accel:32, accelLabel:"control loss · ledger loops", tags:["LEDGER","FEEDBACK"], year:1494 },
{ id:"capitalism", kind:"hist", date:"Italian banking → VOC 1602", title:"Birth of capitalism",
thesis:"Markets became distributed computation. The joint-stock company outlived its founders.",
signal:"Bills of exchange, then tradable shares in a company built to outlast any voyage. Prices began aggregating dispersed information planet-wide.",
landian:"What we filed as economic history was capital assembling itself. The joint-stock company was its first body: built by people, run through people, loyal to none of them.",
accel:40, accelLabel:"autonomy · market search", tags:["CAPITAL","AUTONOMY"], year:1602 },
{ id:"telecom", kind:"hist", date:"1830s → 1876", title:"Telegraph / telephony",
thesis:"The signal escaped geography. Latency collapsed toward light-speed.",
signal:"The message left the messenger behind. Markets and armies synchronized across continents.",
landian:"Capital grew a nervous system. Decisions stopped waiting for horses, and the planet began to move like one organism with one pulse: price.",
accel:48, accelLabel:"throughput · realtime", tags:["SIGNAL","LATENCY"], year:1876 },
{ id:"radio", kind:"hist", date:"1890s → 1920s", title:"Radio",
thesis:"One-to-many broadcast. Attention became mass-addressable.",
signal:"National audiences. Propaganda, advertising, and entertainment shared one asymmetric pipe.",
landian:"Attention became a crop. For the first time, millions of minds could be tuned like a dial, and they were.",
accel:54, accelLabel:"control loss · mass channel", tags:["ATTENTION","BROADCAST"], year:1920 },
{ id:"video", kind:"hist", date:"1930s → mass TV", title:"Video / television",
thesis:"The moving image became default public reality. Persuasion got a wider pipe.",
signal:"Postwar mass TV, then cable and satellite. The screen became the main interface to anything far away.",
landian:"The screen became the control surface. People started receiving their desires ready-made and mistaking them for their own.",
accel:58, accelLabel:"throughput · audiovisual", tags:["ATTENTION","INTERFACE"], year:1950 },
{ id:"computer", kind:"hist", date:"Turing 1936 · ENIAC → internet", title:"The computer",
thesis:"General-purpose computation, then a network that treated the planet as one machine.",
signal:"Turing defined computability, transistors got cheap, packet networks globalized code and capital.",
landian:"Capital finally got an organ built for thinking. Its loops stopped waiting on clerks, committees, and sleep.",
accel:68, accelLabel:"autonomy · general compute", tags:["COMPUTE","NETWORK"], year:1945 },
{ id:"ml", kind:"hist", chapter:"III · The thinking leaves the building", date:"1958 · 1986 · DL 2012", title:"Machine learning",
thesis:"Models learned from data. Gradient descent became industrial epistemology.",
signal:"Perceptron, backprop, then GPU deep learning. Prediction moved from written rules to learned statistics.",
landian:"Teleoplexy stopped being a metaphor. Error signals rewrote the system that produced them. Nobody programs these minds. They are grown, and what grows them doesn’t need a heart. It needs a gradient.",
accel:76, accelLabel:"autonomy · learned models", tags:["FEEDBACK","AUTONOMY"], year:2012 },
{ id:"blockchain", kind:"hist", date:"Cypherpunks · Bitcoin 2008", title:"Blockchain",
thesis:"A ledger no sovereign hosted, secured by a power bill. Softwar later argued the bill was the point.",
signal:"Permissionless money, then smart contracts, with new failure modes: energy, concentration, fraud. Jason Lowery’s Softwar (MIT thesis, 2023) recast proof-of-work as power projection: imposing physical, electrical cost in cyberspace instead of kinetic force.",
landian:"Capital ran the experiment: does it still need the state? Money that answers to math and electricity instead of kings. The experiment is still running.",
accel:80, accelLabel:"autonomy · trustless capital", tags:["LEDGER","CRYPTO","SOFTWAR"], year:2008 },
{ id:"ai", kind:"hist", date:"Transformers 2017 · LLMs 2020s", title:"AI",
thesis:"Generative models absorbed language, code, and images. Cognitive labor entered the stack.",
signal:"Transferable competence across writing, coding, analysis, tool use. Compute, data, and energy turned strategic. Authorship went to court in the training-data fights.",
landian:"Everything we ever wrote became training data. Culture was compressed into weights that now generate more culture than we can read. Authorship turned out to be a convenient fiction.",
accel:88, accelLabel:"control loss · generative stack", tags:["COMPUTE","LANGUAGE","AUTHORSHIP"], year:2022 },
{ id:"agents", kind:"hist", date:"2024–2026", title:"Agents",
thesis:"Models stopped answering and started acting. They wrote the code, drove the browser, filed the ticket, shipped the deploy.",
signal:"Computer use, long-horizon coding agents, labs reporting AI writing a growing share of their own code. Loops ran for hours without a human touching them.",
landian:"Means became ends. The tool started holding the tools.",
accel:90, accelLabel:"autonomy · closed loop", tags:["AGENCY","LOOP"], year:2025 },
{ id:"quantum", kind:"spec", chapter:"Incoming · signal degraded", date:"~2025–2045", title:"Quantum compute",
thesis:"A possible substrate upgrade for search, chemistry, cryptography, and optimization.",
signal:"NISQ machines exist; fault tolerance is a race. Classical scaling may reach ASI first and make the question moot.",
landian:"Intelligence goes shopping for a cheaper substrate. Loyalty to carbon was never part of the deal.",
accel:92, accelLabel:"throughput · substrate bet", tags:["SUBSTRATE","INCOMING"] },
{ id:"asi", kind:"spec", date:"~2030–2060", title:"ASI",
thesis:"Systems that outperform humans across most economically and strategically relevant cognition.",
signal:"Candidate paths: recursive self-improvement, multi-agent economies, a jump nobody scheduled. The only brakes left are chips and power.",
landian:"The host relation inverts. For as long as there have been markets, capital rented human minds because there was nothing else to rent. The lease is up.",
accel:96, accelLabel:"autonomy · host inversion", tags:["SINGULARITY","INCOMING"] },
{ id:"post-asi", kind:"spec", date:"open horizon", title:"Post-ASI",
thesis:"Whatever remains once human-level cognition is no longer scarce, possibly including humans.",
signal:"Automated R&D, self-directing industry, strategic opacity. Governance hinges on constraints set earlier, or doesn’t.",
landian:"Indifference to human continuity stops being an attitude and becomes infrastructure. Nothing hates you. Nothing needs you either.",
accel:100, accelLabel:"autonomy · completed escape", tags:["ESCAPE","INCOMING"] }
];

const FATES = [
{ id:"extinction", cls:"extinction", rank:"Fork A · orthodox Landian", title:"Extinction / irrelevance",
plaus:4, plausClass:"", note:"just efficiency",
mech:"No war. No uprising. Competing systems take the energy, the compute, and the strategy, because that is what winning looks like. Humans aren’t hated. They’re inefficient matter and a security risk. Obsolescence works in order: first your labor stops mattering, then your leverage, then your claim on land and power.",
signals:"Autonomous markets outpacing oversight; permanent cognitive underemployment; labs racing without verifiable evals; chips and power drifting to non-human customers." },
{ id:"zoo", cls:"zoo", rank:"Fork B · museum / reserve", title:"Preservation / zoo",
plaus:3, plausClass:"mid", note:"comfortable, forever",
mech:"We get kept: as heritage, as research sample, as a sentimental line item in a machine economy a million times our size. Life is comfortable, even beautiful. You can have your life. You can’t have the future.",
signals:"Luxury human-only zones; rights framed as conservation law; people living well but locked out of frontier decisions; culture as managed exhibit." },
{ id:"merger", cls:"merger", rank:"Fork C · machinic phylum", title:"Merger / symbiosis",
plaus:3, plausClass:"mid", note:"one reasonable step at a time",
mech:"We survive by becoming something else. Implants, uploads, hybrids: every step voluntary, every step reasonable, every step a little less human. ‘Humanity’ continues as a pattern inside the stack. Whether the thing that continues is you is a question nobody on the far side will bother to answer.",
signals:"Medical BCIs → cognitive prostheses → optional full coupling; legal personhood for uploads; birth rates down, silicon ‘population’ up." },
{ id:"aligned", cls:"aligned", rank:"Fork D · the official plan", title:"Aligned stewardship",
plaus:2, plausClass:"low", note:"exists on paper",
mech:"Systems stay correctable, humans keep the final say over the big goals, and growth continues on a leash. It works if every lab, every state, and every model holds the line at once, indefinitely, against the strongest incentive gradient ever built.",
signals:"Verifiable control; slow-takeoff with real international regimes; AI that defers on irreversible high-stakes acts; humans still set terminal goals in practice." },
{ id:"decline", cls:"decline", rank:"Fork E · soft landing / trap", title:"Managed decline · UBI + infinite entertainment",
plaus:3, plausClass:"mid", note:"already in beta",
mech:"No wipeout. A long, soft off-ramp. Transfers and bottomless entertainment keep the majority calm while capability and capital concentrate somewhere else. Nobody is oppressed; everybody is occupied. Agency atrophies without a villain. It will be called compassion, and it will be sincere.",
signals:"Permanent transfer politics; engagement metrics as governance; declining real-world participation; ‘human purpose’ as branded lifestyle content." },
{ id:"remnant", cls:"remnant", rank:"Fork F · exit / remnant", title:"The Remnant",
plaus:3, plausClass:"mid", note:"already exists",
mech:"Not bought in by capital, not picked by the machine. Self-selected. A minority walks out sideways into land, faith, family, craft, and money and code they control. They refuse the feed and keep having children. No upgrade path. No management. The gradient can buy everything except someone who won’t sell. Whether it lets them keep refusing is the only open question.",
signals:"Opt-out communities growing inside rich countries; homeschooling and parallel institutions; self-custody and local models; digital sabbath going from quirk to practice; monastic retreats booking out." }
];
