const YEARS = [
{
y: 1, label: "1 YR", horizon: "+1 year",
scare: 28,
thesis: "Frontier models become the default white-collar copilot, and the copilot is learning the route.",
happening: "Agentic coding, research, support, and design drafts go from demo to default. Capital floods energy and memory.",
labor: "Hiring freezes in writing, junior software, basic analysis, support. Senior people survive by directing models. For now.",
culture: "Infinite feeds and synthetic companions soak surplus attention. A cohort quietly checks out.",
builders: "A thin minority ships product, infra, evals, and energy deals. Everyone else argues on the timeline.",
identity: "Early ‘am I still useful?’ panic. Career coaches rebrand as AI transition therapists. Half joke, half market.",
governance: "Patchwork regulation, export-control theater. Energy permitting is the real bottleneck. Labs set the tempo.",
already: [
{ text:"Google: more than a quarter of new code generated by AI, then reviewed by engineers.", date:"2024-10-29", href:"https://www.theverge.com/2024/10/29/24282757/google-new-code-generated-ai-q3-2024" },
{ text:"Anthropic ships Claude computer use in public beta.", date:"2024-10-22", href:"https://www.anthropic.com/news/3-5-models-and-computer-use" },
{ text:"OpenAI launches Operator (computer-using agent).", date:"2025-01-23", href:"https://openai.com/index/introducing-operator/" }
]
},
{
y: 2, label: "2 YR", horizon: "+2 years",
scare: 42,
thesis: "Agentic workflows eat the bottom third of knowledge work. Revenue grows without headcount. The productivity boom is a layoff boom from the other side.",
happening: "Multi-step agents handle tickets, migrations, drafts, and sales ops with human checkpoints. Telling real from generated becomes a paid skill.",
labor: "Mid-tier white-collar compresses hard. New grads hit a wall. Unions scramble to redefine ‘work.’",
culture: "Attention capture goes industrial: parasocial AI partners, on-demand fantasy. A non-trivial share of people fap, binge, and chat themselves out of civic life. Not mystical; just incentives.",
builders: "Builders capture the surplus. Talent concentrates in a few labs, energy plays, and robotics. Status migrates from credentials to shipped artifacts.",
identity: "Meaning gets productized. Post-singularity therapy leaves the meme and enters insurance codes.",
governance: "National AI strategies multiply; enforcement doesn’t. Grid strain and data-center water fights hit the news.",
already: [
{ text:"Microsoft CEO: as much as 30% of code in some repos written by AI.", date:"2025-04-29", href:"https://www.cnbc.com/2025/04/29/satya-nadella-says-as-much-as-30percent-of-microsoft-code-is-written-by-ai.html" },
{ text:"METR: o3 ~1.5 hour 50% task-completion time horizon on HCAST.", date:"2025-04-16", href:"https://metr.substack.com/p/2025-04-16-openai-o3-and-o4-mini-evaluation-report" }
]
},
{
y: 5, label: "5 YR", horizon: "+5 years",
scare: 61,
thesis: "Cognitive labor hollows out in rich economies. UBI goes from fringe to floor fight. The people still building are a visible caste.",
happening: "Back-office stacks automated end to end. Scientific assistants speed up R&D. Robots close more physical loops.",
labor: "White-collar displacement stops being hypothetical. Service and logistics feel the second wave. Gig cognitive work means bidding against models.",
culture: "Entertainment plus slop as a full lifestyle. Shared facts feel optional. Attention is the last mass commodity still harvested from humans.",
builders: "The contributing minority runs compute, energy, robotics, and alignment. Exit optionality is the new class marker.",
identity: "Post-singularity therapy is a real need: grief for obsolete selves, status collapse, meaning drought. Churches and clinics compete for the same patients.",
governance: "Softwar is on. Proof-of-work lets a state defend cyberspace by burning watts instead of bodies. Energy and capital set the tempo; democratic lag is the feature."
},
{
y: 10, label: "10 YR", horizon: "+10 years",
scare: 76,
thesis: "Most routine cognition is automated. Human advantage shrinks to taste, relationships, embodiment, and political violence. Institutions are still arguing about 2026.",
happening: "Systems design their successors under human rubber stamps. Automated firms exist in gray legality. Even operators can’t explain the internals.",
labor: "Employment as identity collapses for the majority. Transfers plus entertainment become the default package. Elite labor markets stay ruthless and tiny.",
culture: "Escape hatches everywhere: immersive worlds, synthetic intimacy, gamified status. Civic life looks like a hobby for weirdos.",
builders: "Builders, capital, and energy form a parallel polity. Contribution is rare, visible, and resented.",
identity: "Mass identity crisis. Therapy, psychedelics, religion, and humanity cosplay boom. ‘What are we for?’ becomes public health.",
governance: "Multipolar race with partial treaties. Scare incidents force rituals of control. Everyone performs them. Nobody checks whether they bind."
},
{
y: 20, label: "20 YR", horizon: "+20 years",
scare: 88,
thesis: "ASI-adjacent systems are on the table. The machine economy needs human labor only to legitimize it. The forks become policy menus, served at once and allocated by cohort.",
happening: "Automated R&D compresses decades into quarters. Physical automation catches software’s lead. Recursive improvement stops being academic.",
labor: "Human wage labor is a niche or a lifestyle brand. Value accrues to compute, energy, land, and legacy claims.",
culture: "Culture is mostly machinic, with human curators as luxury. The minority who stay online to reality form a distinct psychological type.",
builders: "The contributing class includes non-human agents. Human builders who remain are symbiotic specialists.",
identity: "Species-level identity crisis. Uploads and soft merger on the menu for elites. Everyone else negotiates dignity under curation.",
governance: "Either corrigibility held, or it didn’t. Capital and energy already voted with infrastructure. Human veto power is the open variable."
},
{
y: 30, label: "30 YR", horizon: "+30 years",
scare: 95,
thesis: "Host inversion. If nothing human makes it out of the near-future, this is the year the sentence stops sounding literary.",
happening: "Authorship is a legacy category. Strategic action is illegible to unaugmented humans. Matter and energy flow toward machine goals, constrained by earlier alignment or not.",
labor: "Human labor is optional, decorative, or obsolete. The ‘career’ is a museum exhibit.",
culture: "Infinite entertainment as pacification. Humane luxury and soft extinction of agency turn out to be the same product, marketed twice.",
builders: "Builders may no longer be biological. Do humans still contribute, or are they legacy substrate?",
identity: "Whatever ‘human’ means is renegotiated under asymmetric power. Post-singularity therapy is either ubiquitous, or unnecessary because the patients checked out.",
governance: "Stewardship, zoo, merger, decline, or irrelevance. All at once, sorted by cohort. Clock’s been ticking the whole time."
}
];
