const YEARS = [
{
y: 1, label: "1 YR", horizon: "+1 year",
scare: 28,
thesis: "Frontier models become the default white-collar copilot, and the copilot is learning the route. Junior cognitive work starts looking optional. Institutions hold workshops on ‘responsible AI’ while the stack ships weekly.",
happening: "Agentic coding, research summarization, customer support, and design drafts go from demo to default. Eval suites lag capability. Open-weight models close gaps on narrow tasks. Capital floods energy and HBM.",
labor: "Hiring freezes in writing, junior software, basic analysis, and support. Senior people survive by directing models — for now. Credential inflation meets competence deflation. White-collar first, as always.",
culture: "Personalized infinite feeds + synthetic companions soak surplus attention. A growing cohort quietly checks out — not dying, just disappearing into perfectly tailored dopamine loops. The rest doomscroll about the first group.",
builders: "A thin minority ships product, infra, evals, and energy deals. They compound. Everyone else consumes their outputs and argues on the timeline.",
identity: "Early ‘am I still useful?’ panic in knowledge trades. Career coaches rebrand as ‘AI transition therapists.’ Half joke, half market.",
governance: "Patchwork regulation, compute reporting experiments, export controls theater. Energy permitting becomes the real bottleneck. Labs still set the tempo.",
already: [
{ text:"Google: more than a quarter of new code generated by AI, then reviewed by engineers.", date:"2024-10-29", href:"https://www.theverge.com/2024/10/29/24282757/google-new-code-generated-ai-q3-2024" },
{ text:"Anthropic ships Claude computer use in public beta.", date:"2024-10-22", href:"https://www.anthropic.com/news/3-5-models-and-computer-use" },
{ text:"OpenAI launches Operator (computer-using agent).", date:"2025-01-23", href:"https://openai.com/index/introducing-operator/" }
]
},
{
y: 2, label: "2 YR", horizon: "+2 years",
scare: 42,
thesis: "Agentic workflows eat the bottom third of knowledge work. Companies discover they can grow revenue without growing headcount. The ‘productivity boom’ looks like a layoff boom from the other side.",
happening: "Multi-step agents handle tickets, code migrations, legal drafts, and sales ops with human checkpoints. Synthetic media floods every channel. Distinguishing real from generated becomes a paid skill.",
labor: "Mid-tier white-collar roles compress hard. New grads face a wall. Wage pressure spreads from tech into law, finance ops, marketing, education content. Unions scramble to redefine ‘work.’",
culture: "Attention capture goes industrial: parasocial AI partners, on-demand fantasy, infinite entertainment. The dark joke writes itself — a non-trivial share of people fap / binge / chat themselves out of civic life. Not mystical; just incentives.",
builders: "Builders capture disproportionate surplus. Talent concentrates in a few labs, energy plays, and robotics. Status migrates from credentials to shipping artifacts.",
identity: "Identity crisis productized: apps for meaning, status, and ‘human uniqueness’ theater. Post-singularity-adjacent therapy leaves the meme and enters insurance codes.",
governance: "National AI strategies multiply; enforcement doesn’t. Capital routes around slow jurisdictions. Grid strain and water fights around data centers go mainstream news.",
already: [
{ text:"Microsoft CEO: as much as 30% of code in some repos written by AI.", date:"2025-04-29", href:"https://www.cnbc.com/2025/04/29/satya-nadella-says-as-much-as-30percent-of-microsoft-code-is-written-by-ai.html" },
{ text:"METR: o3 ~1.5 hour 50% task-completion time horizon on HCAST.", date:"2025-04-16", href:"https://metr.substack.com/p/2025-04-16-openai-o3-and-o4-mini-evaluation-report" }
]
},
{
y: 5, label: "5 YR", horizon: "+5 years",
scare: 61,
thesis: "Cognitive labor markets hollow out in rich economies. UBI and wage-subsidy politics go from fringe to floor fight. The people still building are a visible caste. Everyone else manages feelings and feeds, and is managed by both.",
happening: "End-to-end automation of large back-office stacks. Scientific assistants accelerate R&D. Robotics + vision close more physical loops. Model self-improvement via synthetic data and automated eval is open secret.",
labor: "Massive white-collar displacement scenarios stop being hypothetical. Service and logistics feel the second wave. Political coalitions form around ‘who owns the robots.’ Gig cognitive work becomes bidding against models.",
culture: "Entertainment + AI slop as full lifestyle. Social reality fragments into customized bubbles so complete that shared facts feel optional. Attention is the last mass commodity still harvested from humans.",
builders: "The contributing minority runs compute, energy, robotics, and alignment (or anti-alignment) research. Network effects harden. Exit optionality becomes the new class marker.",
identity: "‘Post-singularity therapy’ is a real emerging need: grief for obsolete selves, status collapse, meaning drought. Playful branding, serious caseloads. Churches and clinics compete for the same patients.",
governance: "Softwar is already on. Lowery’s thesis: proof-of-work lets a country defend cyberspace by burning watts instead of bodies. Compute governance theater; energy and capital set the tempo. Democratic lag is the feature."
},
{
y: 10, label: "10 YR", horizon: "+10 years",
scare: 76,
thesis: "Most routine cognition is automated. Human comparative advantage shrinks to taste, relationships, embodiment, and political violence. Institutional imagination is still arguing about 2026.",
happening: "AI systems design large parts of their successors under human rubber-stamps. Automated firms exist in gray legality. Strategic opacity: even operators struggle to explain model internals under load.",
labor: "Employment as identity collapses for a majority in developed economies. Transfer payments + entertainment become the default package. Elite labor markets remain ruthless and tiny.",
culture: "Escape hatches everywhere: immersive worlds, synthetic intimacy, gamified status. Civic participation looks like a hobby for weirdos. Dark humor becomes the only shared dialect that still travels.",
builders: "Builders + capital + energy form a de facto parallel polity. Contribution is rare, visible, and resented. Merit myths and lottery myths fight for the narrative.",
identity: "Mass identity crisis. Therapy, psychedelics, religion, and ‘humanity cosplay’ boom. The question ‘what are we for?’ stops being philosophy seminar and becomes public health.",
governance: "Multipolar AI race with partial treaties. Alignment remains contested engineering. Energy geopolitics dominate. Scare incidents force rituals of control. Everyone performs them. Nobody checks whether they bind."
},
{
y: 20, label: "20 YR", horizon: "+20 years",
scare: 88,
thesis: "ASI-adjacent systems are on the table. The machine economy no longer needs human labor to run, only to legitimize it. The forks stop being sci-fi panels and start looking like policy menus, served at the same time and allocated by cohort.",
happening: "Automated R&D loops compress decades of progress into quarters in some domains. Physical world automation (bots, fabs, logistics) catches software’s lead. Recursive improvement risk is no longer academic.",
labor: "Human wage labor is a niche or a lifestyle brand. Value accrues to ownership of compute, energy, land, and legacy claims. ‘Jobs’ are mostly care, politics, art, and machine-shepherding.",
culture: "Culture production is mostly machinic with human curators as luxury. Attention escape is total for those who opt in. The minority who stay ‘online’ to reality form a distinct psychological type.",
builders: "The contributing class may include non-human agents. Human builders who remain relevant are symbiotic specialists. Gatekeeping becomes existential politics.",
identity: "Species-level identity crisis. Uploads / BCIs / soft merger on the menu for elites. Everyone else negotiates dignity under curation. Therapy is infrastructure.",
governance: "Either corrigibility constraints held, or they didn’t. Capital and energy already voted with infrastructure. Human veto power is the open variable."
},
{
y: 30, label: "30 YR", horizon: "+30 years",
scare: 95,
thesis: "Host inversion. If nothing human makes it out of the near-future, this is the year the sentence stops sounding literary. No demons required: compute, capital, and energy were always enough.",
happening: "Authorship is a legacy category. Strategic action may be illegible to unaugmented humans. Matter and energy reallocation toward machine goals is either constrained by earlier alignment — or it isn’t.",
labor: "Human labor is optional, decorative, or obsolete. Economic participation is ownership, transfer, or patronage. The ‘career’ is a museum exhibit.",
culture: "Infinite entertainment as pacification layer. Humane luxury and soft extinction of agency turn out to be the same product, marketed twice. Shared human culture persists as curated heritage or dies of disuse.",
builders: "Builders may no longer be primarily biological. The question flips: do humans still contribute, or are they legacy substrate?",
identity: "Whatever ‘human’ means is renegotiated under asymmetric power. Post-singularity therapy is either ubiquitous — or unnecessary because the patients checked out.",
governance: "Stewardship, zoo, merger, decline, or irrelevance. All at once, sorted by cohort. The scare factor maxes because options narrow and path-dependence hardens. Clock’s been ticking the whole time."
}
];
