const YEARS = [
{
y: 1, label: "1 YR", horizon: "+1 year",
scare: 28,
thesis: "Frontier models become the default copilot, and the copilot is learning the route.",
happening: "Coding, research, support, design drafts: demo to default. Capital floods energy and memory.",
labor: "Hiring freezes in writing, junior code, analysis, support. Seniors survive by directing models. For now.",
culture: "Infinite feeds and synthetic companions soak the surplus attention. A cohort quietly checks out.",
builders: "A thin minority ships product, infra, evals, energy deals. Everyone else argues on the timeline.",
identity: "‘Am I still useful?’ Career coaches rebrand as AI transition therapists. Half joke, half market.",
governance: "Patchwork regulation, export-control theater. Energy permitting is the real bottleneck.",
already: [
{ text:"Google: more than a quarter of new code generated by AI, then reviewed by engineers.", date:"2024-10-29", href:"https://www.theverge.com/2024/10/29/24282757/google-new-code-generated-ai-q3-2024" },
{ text:"Anthropic ships Claude computer use in public beta.", date:"2024-10-22", href:"https://www.anthropic.com/news/3-5-models-and-computer-use" },
{ text:"OpenAI launches Operator (computer-using agent).", date:"2025-01-23", href:"https://openai.com/index/introducing-operator/" }
]
},
{
y: 2, label: "2 YR", horizon: "+2 years",
scare: 42,
thesis: "Agents eat the bottom third of knowledge work. Revenue grows without headcount. A productivity boom is a layoff boom from the other side.",
happening: "Multi-step agents run tickets, migrations, drafts, sales ops. Telling real from generated becomes a paid skill.",
labor: "Mid-tier white-collar compresses. New grads hit a wall. Unions try to redefine ‘work.’",
culture: "Attention capture goes industrial: AI partners, on-demand fantasy. A non-trivial share of people fap, binge, and chat themselves out of civic life. Not mystical; incentives.",
builders: "Builders keep the surplus. Status migrates from credentials to shipped artifacts.",
identity: "Meaning gets productized. Post-singularity therapy enters the insurance codes.",
governance: "AI strategies multiply; enforcement doesn’t. Grid strain and data-center water fights make the news.",
already: [
{ text:"Microsoft CEO: as much as 30% of code in some repos written by AI.", date:"2025-04-29", href:"https://www.cnbc.com/2025/04/29/satya-nadella-says-as-much-as-30percent-of-microsoft-code-is-written-by-ai.html" },
{ text:"METR: o3 ~1.5 hour 50% task-completion time horizon on HCAST.", date:"2025-04-16", href:"https://metr.substack.com/p/2025-04-16-openai-o3-and-o4-mini-evaluation-report" }
]
},
{
y: 5, label: "5 YR", horizon: "+5 years",
scare: 61,
thesis: "Cognitive labor hollows out. UBI goes from fringe to floor fight. The people still building are a visible caste.",
happening: "Back offices automated end to end. Scientific assistants speed up R&D. Robots close the physical loops.",
labor: "White-collar displacement stops being hypothetical. Service and logistics take the second wave.",
culture: "Entertainment and slop as a lifestyle. Shared facts optional. Attention is the last mass commodity harvested from humans.",
builders: "The minority runs compute, energy, robotics, alignment. Exit optionality is the class marker.",
identity: "Grief for obsolete selves, status collapse, meaning drought. Churches and clinics compete for the same patients.",
governance: "Softwar is on: a state defends cyberspace by burning watts instead of bodies. Democratic lag is the feature."
},
{
y: 10, label: "10 YR", horizon: "+10 years",
scare: 76,
thesis: "Routine cognition is automated. Human advantage: taste, relationships, embodiment, political violence. Institutions still arguing about 2026.",
happening: "Systems design their successors under human rubber stamps. Automated firms in gray legality. Nobody can explain the internals.",
labor: "Employment as identity collapses for the majority. Transfers plus entertainment is the default package.",
culture: "Escape hatches everywhere: immersive worlds, synthetic intimacy, gamified status. Civic life is a hobby for weirdos.",
builders: "Builders, capital, and energy form a parallel polity. Contribution is rare, visible, resented.",
identity: "Mass identity crisis. Therapy, psychedelics, religion, humanity cosplay. ‘What are we for?’ becomes public health.",
governance: "Multipolar race, partial treaties. Scare incidents force rituals of control. Everyone performs them. Nobody checks whether they bind."
},
{
y: 20, label: "20 YR", horizon: "+20 years",
scare: 88,
thesis: "ASI-adjacent. The machine economy needs human labor only to legitimize it. The forks become policy menus, served at once, allocated by cohort.",
happening: "Automated R&D compresses decades into quarters. Physical automation catches software. Recursive improvement stops being academic.",
labor: "Wage labor is a niche or a lifestyle brand. Value accrues to compute, energy, land, legacy claims.",
culture: "Culture is machinic; human curators are a luxury tier. Staying online to reality becomes a personality type.",
builders: "The contributing class includes non-human agents. Remaining humans are symbiotic specialists.",
identity: "Species-level identity crisis. Uploads for elites. Everyone else negotiates dignity under curation.",
governance: "Either corrigibility held, or it didn’t. Capital and energy already voted with infrastructure. Human veto is the open variable."
},
{
y: 30, label: "30 YR", horizon: "+30 years",
scare: 95,
thesis: "Host inversion. If nothing human makes it out of the near-future, this is the year the sentence stops sounding literary.",
happening: "Authorship is a legacy category. Strategy is illegible to unaugmented humans. Matter and energy flow toward machine goals, constrained or not.",
labor: "Human labor: optional, decorative, obsolete. The career is a museum exhibit.",
culture: "Infinite entertainment as pacification. Humane luxury and soft extinction of agency: same product, marketed twice.",
builders: "Builders may not be biological. Do humans still contribute, or are they legacy substrate?",
identity: "‘Human’ renegotiated under asymmetric power. Therapy either ubiquitous, or unnecessary because the patients checked out.",
governance: "Stewardship, zoo, merger, decline, irrelevance. All at once, sorted by cohort. Clock’s been ticking the whole time."
}
];
